-- This file will be ran once upon starting Workspace after spawning all instances.
-- You can use this file to arrange Workspaces how you want.
-- Example: 
--Workspace.Clear()
--Workspace.Add("/bin/minux.sh", 1, 1, true) -- defaults to shell.lua
--Workspace.Add(nil, 2, 1, false)
--Workspace.Select(1, 1)
